import { StyleSheet } from "react-native";
import { Theme } from "./themes";

export const createDetailsStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    contentContainer: {
      padding: 20,
      paddingTop: 54,
      paddingBottom: 36,
    },
    header: {
      fontSize: 28,
      fontWeight: "800",
      color: theme.text,
      flex: 1,
      marginRight: 12,
    },
    sectionLabel: {
      fontSize: 12,
      fontWeight: "800",
      color: theme.textSecondary,
      textTransform: "uppercase",
      marginTop: 20,
      marginBottom: 8,
    },
    text: {
      fontSize: 16,
      marginBottom: 12,
      color: theme.text,
      lineHeight: 24,
    },
    textSecondary: {
      fontSize: 14,
      color: theme.textSecondary,
      marginBottom: 8,
    },
    detailsCard: {
      backgroundColor: theme.surface,
      padding: 18,
      borderRadius: 8,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 2,
    },
    heroCard: {
      backgroundColor: theme.surface,
      padding: 20,
      borderRadius: 8,
      marginBottom: 18,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 3,
    },
    heroIcon: {
      width: 46,
      height: 46,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.primarySoft,
      marginBottom: 14,
    },
    statusPill: {
      alignSelf: "flex-start",
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 6,
      marginTop: 12,
    },
    statusPillText: {
      fontSize: 12,
      fontWeight: "900",
      textTransform: "uppercase",
    },
    detailsGrid: {
      gap: 12,
    },
    detailRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      backgroundColor: theme.surface,
      padding: 16,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
    },
    detailIcon: {
      width: 36,
      height: 36,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.primarySoft,
      marginRight: 12,
    },
    detailLabel: {
      color: theme.textSecondary,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      marginBottom: 4,
    },
    detailValue: {
      color: theme.text,
      fontSize: 16,
      fontWeight: "700",
      lineHeight: 22,
    },
    input: {
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.background,
      color: theme.text,
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 8,
    },
    passwordInputContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.background,
      borderRadius: 8,
      marginBottom: 8,
    },
    passwordInput: {
      flex: 1,
      color: theme.text,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    iconButton: {
      padding: 12,
    },
    inputError: {
      borderColor: "#D92D20",
      backgroundColor: theme.errorBackground,
    },
    errorText: {
      color: "#D92D20",
      fontSize: 12,
      fontWeight: "700",
      marginBottom: 8,
    },
    dateTimeContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },
    dateText: {
      fontSize: 18,
      fontWeight: "600",
      color: theme.primary,
    },
    timeText: {
      fontSize: 18,
      fontWeight: "600",
      color: theme.primary,
    },
    buttonContainer: {
      marginTop: 24,
      gap: 12,
    },
    editButton: {
      backgroundColor: theme.primary,
      paddingVertical: 15,
      borderRadius: 8,
      alignItems: "center",
    },
    editButtonText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "600",
    },
    secondaryButton: {
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.background,
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderRadius: 8,
      alignItems: "center",
      marginTop: 10,
    },
    secondaryButtonText: {
      color: theme.primary,
      fontSize: 15,
      fontWeight: "800",
    },
    deleteButton: {
      backgroundColor: "#FF6B6B",
      paddingVertical: 15,
      borderRadius: 8,
      alignItems: "center",
    },
    deleteButtonText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "600",
    },
    accountRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      borderTopWidth: 1,
      borderTopColor: theme.border,
      paddingTop: 14,
      marginTop: 14,
      gap: 12,
    },
    accountName: {
      color: theme.text,
      fontSize: 15,
      fontWeight: "800",
      marginBottom: 4,
    },
    accountDetail: {
      color: theme.textSecondary,
      fontSize: 13,
      lineHeight: 20,
    },
    roleBadge: {
      color: theme.primary,
      borderColor: theme.primary,
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 4,
      fontSize: 12,
      fontWeight: "900",
      textTransform: "uppercase",
    },
  });

export const detailsStyles = createDetailsStyles;
